### PR TITLE
Main.py

### PR DESCRIPTION
**Pull request by pranavjha2426**

### CODE REVIEW

**Comment by pranavjha2426** [comment]
Hmm

**Comment by LEGENDXOP** [comment]
Bhaag beti chod

**Comment by srinivasop** [comment]
😶😶

**Comment by ghost** [comment]
@LEGENDXOP .

**Comment by ghost** [comment]
@pranavjha21 Abe maine kha kiya

**Comment by srinivasop** [comment]
@pranavjha21 Kuch nahi

**Comment by LEGENDXOP** [comment]
> @pranavjha21 Abe maine kha kiya

Bhaag lode

**Comment by srinivasop** [comment]
@LEGENDXOP Ale 😂

**Comment by LEGENDXOP** [comment]
> @LEGENDXOP Ale 😂

🤔🤔🤔

**Pull request merged**
